# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ethan/iMay/ThreadPool

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ethan/iMay/ThreadPool

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ethan/iMay/ThreadPool/CMakeFiles /home/ethan/iMay/ThreadPool/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ethan/iMay/ThreadPool/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ThreadPool

# Build rule for target.
ThreadPool: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ThreadPool
.PHONY : ThreadPool

# fast build rule for target.
ThreadPool/fast:
	$(MAKE) -f CMakeFiles/ThreadPool.dir/build.make CMakeFiles/ThreadPool.dir/build
.PHONY : ThreadPool/fast

BusyThreadContainer.o: BusyThreadContainer.cpp.o

.PHONY : BusyThreadContainer.o

# target to build an object file
BusyThreadContainer.cpp.o:
	$(MAKE) -f CMakeFiles/ThreadPool.dir/build.make CMakeFiles/ThreadPool.dir/BusyThreadContainer.cpp.o
.PHONY : BusyThreadContainer.cpp.o

BusyThreadContainer.i: BusyThreadContainer.cpp.i

.PHONY : BusyThreadContainer.i

# target to preprocess a source file
BusyThreadContainer.cpp.i:
	$(MAKE) -f CMakeFiles/ThreadPool.dir/build.make CMakeFiles/ThreadPool.dir/BusyThreadContainer.cpp.i
.PHONY : BusyThreadContainer.cpp.i

BusyThreadContainer.s: BusyThreadContainer.cpp.s

.PHONY : BusyThreadContainer.s

# target to generate assembly for a file
BusyThreadContainer.cpp.s:
	$(MAKE) -f CMakeFiles/ThreadPool.dir/build.make CMakeFiles/ThreadPool.dir/BusyThreadContainer.cpp.s
.PHONY : BusyThreadContainer.cpp.s

IdleThreadContainer.o: IdleThreadContainer.cpp.o

.PHONY : IdleThreadContainer.o

# target to build an object file
IdleThreadContainer.cpp.o:
	$(MAKE) -f CMakeFiles/ThreadPool.dir/build.make CMakeFiles/ThreadPool.dir/IdleThreadContainer.cpp.o
.PHONY : IdleThreadContainer.cpp.o

IdleThreadContainer.i: IdleThreadContainer.cpp.i

.PHONY : IdleThreadContainer.i

# target to preprocess a source file
IdleThreadContainer.cpp.i:
	$(MAKE) -f CMakeFiles/ThreadPool.dir/build.make CMakeFiles/ThreadPool.dir/IdleThreadContainer.cpp.i
.PHONY : IdleThreadContainer.cpp.i

IdleThreadContainer.s: IdleThreadContainer.cpp.s

.PHONY : IdleThreadContainer.s

# target to generate assembly for a file
IdleThreadContainer.cpp.s:
	$(MAKE) -f CMakeFiles/ThreadPool.dir/build.make CMakeFiles/ThreadPool.dir/IdleThreadContainer.cpp.s
.PHONY : IdleThreadContainer.cpp.s

MyTask.o: MyTask.cpp.o

.PHONY : MyTask.o

# target to build an object file
MyTask.cpp.o:
	$(MAKE) -f CMakeFiles/ThreadPool.dir/build.make CMakeFiles/ThreadPool.dir/MyTask.cpp.o
.PHONY : MyTask.cpp.o

MyTask.i: MyTask.cpp.i

.PHONY : MyTask.i

# target to preprocess a source file
MyTask.cpp.i:
	$(MAKE) -f CMakeFiles/ThreadPool.dir/build.make CMakeFiles/ThreadPool.dir/MyTask.cpp.i
.PHONY : MyTask.cpp.i

MyTask.s: MyTask.cpp.s

.PHONY : MyTask.s

# target to generate assembly for a file
MyTask.cpp.s:
	$(MAKE) -f CMakeFiles/ThreadPool.dir/build.make CMakeFiles/ThreadPool.dir/MyTask.cpp.s
.PHONY : MyTask.cpp.s

MyThread.o: MyThread.cpp.o

.PHONY : MyThread.o

# target to build an object file
MyThread.cpp.o:
	$(MAKE) -f CMakeFiles/ThreadPool.dir/build.make CMakeFiles/ThreadPool.dir/MyThread.cpp.o
.PHONY : MyThread.cpp.o

MyThread.i: MyThread.cpp.i

.PHONY : MyThread.i

# target to preprocess a source file
MyThread.cpp.i:
	$(MAKE) -f CMakeFiles/ThreadPool.dir/build.make CMakeFiles/ThreadPool.dir/MyThread.cpp.i
.PHONY : MyThread.cpp.i

MyThread.s: MyThread.cpp.s

.PHONY : MyThread.s

# target to generate assembly for a file
MyThread.cpp.s:
	$(MAKE) -f CMakeFiles/ThreadPool.dir/build.make CMakeFiles/ThreadPool.dir/MyThread.cpp.s
.PHONY : MyThread.cpp.s

MyThreadPool.o: MyThreadPool.cpp.o

.PHONY : MyThreadPool.o

# target to build an object file
MyThreadPool.cpp.o:
	$(MAKE) -f CMakeFiles/ThreadPool.dir/build.make CMakeFiles/ThreadPool.dir/MyThreadPool.cpp.o
.PHONY : MyThreadPool.cpp.o

MyThreadPool.i: MyThreadPool.cpp.i

.PHONY : MyThreadPool.i

# target to preprocess a source file
MyThreadPool.cpp.i:
	$(MAKE) -f CMakeFiles/ThreadPool.dir/build.make CMakeFiles/ThreadPool.dir/MyThreadPool.cpp.i
.PHONY : MyThreadPool.cpp.i

MyThreadPool.s: MyThreadPool.cpp.s

.PHONY : MyThreadPool.s

# target to generate assembly for a file
MyThreadPool.cpp.s:
	$(MAKE) -f CMakeFiles/ThreadPool.dir/build.make CMakeFiles/ThreadPool.dir/MyThreadPool.cpp.s
.PHONY : MyThreadPool.cpp.s

TaskContainer.o: TaskContainer.cpp.o

.PHONY : TaskContainer.o

# target to build an object file
TaskContainer.cpp.o:
	$(MAKE) -f CMakeFiles/ThreadPool.dir/build.make CMakeFiles/ThreadPool.dir/TaskContainer.cpp.o
.PHONY : TaskContainer.cpp.o

TaskContainer.i: TaskContainer.cpp.i

.PHONY : TaskContainer.i

# target to preprocess a source file
TaskContainer.cpp.i:
	$(MAKE) -f CMakeFiles/ThreadPool.dir/build.make CMakeFiles/ThreadPool.dir/TaskContainer.cpp.i
.PHONY : TaskContainer.cpp.i

TaskContainer.s: TaskContainer.cpp.s

.PHONY : TaskContainer.s

# target to generate assembly for a file
TaskContainer.cpp.s:
	$(MAKE) -f CMakeFiles/ThreadPool.dir/build.make CMakeFiles/ThreadPool.dir/TaskContainer.cpp.s
.PHONY : TaskContainer.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/ThreadPool.dir/build.make CMakeFiles/ThreadPool.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/ThreadPool.dir/build.make CMakeFiles/ThreadPool.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/ThreadPool.dir/build.make CMakeFiles/ThreadPool.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ThreadPool"
	@echo "... BusyThreadContainer.o"
	@echo "... BusyThreadContainer.i"
	@echo "... BusyThreadContainer.s"
	@echo "... IdleThreadContainer.o"
	@echo "... IdleThreadContainer.i"
	@echo "... IdleThreadContainer.s"
	@echo "... MyTask.o"
	@echo "... MyTask.i"
	@echo "... MyTask.s"
	@echo "... MyThread.o"
	@echo "... MyThread.i"
	@echo "... MyThread.s"
	@echo "... MyThreadPool.o"
	@echo "... MyThreadPool.i"
	@echo "... MyThreadPool.s"
	@echo "... TaskContainer.o"
	@echo "... TaskContainer.i"
	@echo "... TaskContainer.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

